# Automatically generated by Pynguin.
import pycallnumber.exceptions as module_0

def test_case_0():
    options_error_0 = module_0.OptionsError()