/*
 * This file was automatically generated by EvoSuite
 * Fri Nov 11 14:04:39 GMT 2022
 */

package es.bsc.dataclay.exceptions;

import org.junit.Test;
import static org.junit.Assert.*;
import es.bsc.dataclay.exceptions.DataClayClassNotFoundException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class DataClayClassNotFoundException_ESTest extends DataClayClassNotFoundException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      DataClayClassNotFoundException dataClayClassNotFoundException0 = new DataClayClassNotFoundException();
      DataClayClassNotFoundException dataClayClassNotFoundException1 = new DataClayClassNotFoundException("dS)y#Dy,", dataClayClassNotFoundException0, true, true);
      assertFalse(dataClayClassNotFoundException1.equals((Object)dataClayClassNotFoundException0));
  }
}
