/*
 * This file was automatically generated by EvoSuite
 * Wed Oct 26 01:34:55 GMT 2022
 */

package com.socialmetrix.mail;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.socialmetrix.mail.Mail;
import com.socialmetrix.mail.MailSender;
import com.socialmetrix.mail.RetrierMailSender;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class RetrierMailSender_ESTest extends RetrierMailSender_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      MailSender mailSender0 = mock(MailSender.class, new ViolatedAssumptionAnswer());
      RetrierMailSender retrierMailSender0 = new RetrierMailSender(1, (-829), 1, mailSender0);
      RetrierMailSender retrierMailSender1 = new RetrierMailSender((-829), 1, (-829), retrierMailSender0);
      RetrierMailSender retrierMailSender2 = new RetrierMailSender(1283, 0, 1224, retrierMailSender1);
      // Undeclared exception!
      try { 
        retrierMailSender2.send((Mail) null);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.socialmetrix.mail.RetrierMailSender", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      MailSender mailSender0 = mock(MailSender.class, new ViolatedAssumptionAnswer());
      RetrierMailSender retrierMailSender0 = new RetrierMailSender(3222, (-973), (-345), mailSender0);
      retrierMailSender0.send((Mail) null);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      RetrierMailSender retrierMailSender0 = new RetrierMailSender(6, 6, 6, (MailSender) null);
      // Undeclared exception!
      try { 
        retrierMailSender0.send((Mail) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      RetrierMailSender retrierMailSender0 = new RetrierMailSender((-407), (-407), (-407), (MailSender) null);
      // Undeclared exception!
      try { 
        retrierMailSender0.send((Mail) null);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.socialmetrix.mail.RetrierMailSender", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      MailSender mailSender0 = mock(MailSender.class, new ViolatedAssumptionAnswer());
      RetrierMailSender retrierMailSender0 = new RetrierMailSender((-1952), (-1952), (-1952), mailSender0);
      RetrierMailSender retrierMailSender1 = new RetrierMailSender(1, 1, (-1952), retrierMailSender0);
      RetrierMailSender.FailureListener retrierMailSender_FailureListener0 = mock(RetrierMailSender.FailureListener.class, new ViolatedAssumptionAnswer());
      retrierMailSender1.setListener(retrierMailSender_FailureListener0);
      // Undeclared exception!
      try { 
        retrierMailSender1.send((Mail) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // timeout value is negative
         //
         verifyException("java.lang.Thread", e);
      }
  }
}
