/*
 * This file was automatically generated by EvoSuite
 * Thu Nov 10 02:18:06 GMT 2022
 */

package org.jomni;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jomni.MapperException;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class MapperException_ESTest extends MapperException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Class<Integer> class0 = Integer.class;
      Class<Object> class1 = Object.class;
      MapperException mapperException0 = MapperException.noResolverFoundFor(class0, class1);
      assertEquals(MapperException.Error.CANNOT_FIND_RESOLVER, mapperException0.getError());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Class<Integer> class0 = Integer.class;
      MapperException mapperException0 = MapperException.noResolverFoundFor(class0, class0);
      MapperException.Error mapperException_Error0 = MapperException.Error.CANNOT_FIND_RESOLVER;
      boolean boolean0 = mapperException0.isError(mapperException_Error0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Class<Object> class0 = Object.class;
      MapperException mapperException0 = MapperException.noResolverFoundFor(class0, class0);
      MapperException.Error mapperException_Error0 = mapperException0.getError();
      assertEquals(MapperException.Error.CANNOT_FIND_RESOLVER, mapperException_Error0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Class<Integer> class0 = Integer.class;
      // Undeclared exception!
      try { 
        MapperException.noResolverFoundFor((Class) null, class0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.jomni.MapperException", e);
      }
  }
}
