# Automatically generated by Pynguin.
import securenative.exceptions.securenative_invalid_uri_exception as module_0

def test_case_0():
    secure_native_invalid_uri_exception_0 = module_0.SecureNativeInvalidUriException()