/*
 * This file was automatically generated by EvoSuite
 * Sat Nov 19 21:52:13 GMT 2022
 */

package io.github.josevjunior.simplejdbc;

import org.junit.Test;
import static org.junit.Assert.*;
import io.github.josevjunior.simplejdbc.JdbcException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class JdbcException_ESTest extends JdbcException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      JdbcException jdbcException0 = new JdbcException("y}8");
      JdbcException jdbcException1 = new JdbcException(jdbcException0);
      assertFalse(jdbcException1.equals((Object)jdbcException0));
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      JdbcException jdbcException0 = new JdbcException("y}8");
      JdbcException jdbcException1 = new JdbcException("s//Cd0;a6O", jdbcException0);
      assertFalse(jdbcException1.equals((Object)jdbcException0));
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      JdbcException jdbcException0 = new JdbcException();
  }
}
